author: TheIronMinerLv
website: www.siderealms.com
name: SurvivalPortals
description: Plugin for handling portal stuff in Side Survival server

main: lv.sidesurvival.SurvivalPortals
version: 2.0
api-version: '1.21'
load: POSTWORLD
depend: [SideLang, WorldGuard, SurvivalZemes]

commands:
  portal:
    aliases: [portals, p]
    description: Main portal command
