author: TheIronMinerLv
website: www.side.lv
name: SurvivalPortals
description: Plugin for handling portal stuff in Side Survival server

main: lv.theironminerlv.sidesurvivalportals.SurvivalPortals
version: 1.0
api-version: 1.18
load: POSTWORLD
depend: [WorldGuard, SurvivalCoreBukkit, SurvivalZemes, Proton]

commands:
  portal:
    aliases: [portals, p]
    description: Main portal command
